package edu.uta.cse.scope.visitor;
import parser.ast.nodes.ModelUnit;
import parser.ast.nodes.OpenDecl;
import parser.ast.nodes.SigDecl;
import parser.ast.nodes.Predicate;
import parser.ast.nodes.Check;
import parser.ast.nodes.Run;

import java.lang.management.MemoryType;
import java.util.ArrayList;
import java.util.List;


import parser.ast.nodes.Assertion;
import parser.ast.nodes.Fact;
import parser.ast.nodes.Function;
import parser.ast.nodes.Body;
import parser.ast.nodes.ConstExpr;
import parser.ast.nodes.LetExpr;
import parser.ast.nodes.ITEFormula;
import parser.ast.nodes.ITEExpr;
import parser.ast.nodes.ITEExprOrFormula;
import parser.ast.nodes.QtFormula;
import parser.ast.nodes.RelDecl;
import parser.ast.nodes.QtExpr;
import parser.ast.nodes.QtExprOrFormula;
import parser.ast.nodes.CallFormula;
import parser.ast.nodes.CallExpr;
import parser.ast.nodes.ListFormula;
import parser.ast.nodes.ListExpr;
import parser.ast.nodes.BinaryFormula;
import parser.ast.nodes.BinaryExpr;
import parser.ast.nodes.UnaryFormula;
import parser.ast.nodes.UnaryExpr;
import parser.ast.nodes.VarExpr;
import parser.ast.nodes.BinaryExpr.BinaryOp;
import parser.ast.nodes.FieldExpr;
import parser.ast.nodes.SigExpr;
import parser.ast.nodes.ExprOrFormula;
import parser.ast.nodes.VarDecl;
import parser.ast.nodes.ParamDecl;
import parser.ast.nodes.PredOrFun;
import parser.ast.nodes.FieldDecl;
import parser.ast.nodes.ModuleDecl;
import parser.ast.nodes.Node;
import parser.ast.visitor.GenericVisitor;
import parser.ast.visitor.PrettyStringVisitor;
import parser.etc.Pair;

import edu.uta.cse.scope.macros.QuantiVar;
import edu.uta.cse.scope.macros.ModelEnv;
import edu.uta.cse.scope.macros.NormalForm;
import edu.uta.cse.scope.macros.QuantificationTreeNode;
import edu.uta.cse.scope.macros.EGraphNode.Metatype;
import edu.uta.cse.scope.macros.EGraphNode.Opcode;
import edu.uta.cse.scope.macros.EGraphNode;

/**
 * This visitor generates the normal form of formulas and functions in the Alloy model. 
 * The normal form consists of a quantification tree and a matrix e-graph representation of the formula or function. 
 * The quantification tree captures the structure of the quantifiers in the formula or function, while the matrix e-graph captures the structure of the formula or function itself.
 * The normal form can be used for distance calculation, as well as for other analyses and transformations on the formula or function.
 */
public class NormalFormVisitor implements GenericVisitor<EGraphNode, NormalForm> {
    private List<NormalForm> normalForms; // the list of normal forms generated by this visitor, one for each formula or function in the model.
    private ModelEnv modelEnv; // the model environment, which contains the global declarations in the model, such as signatures, fields, predicates, functions, facts, assertions, etc. It can
    // be used to resolve the references in the formulas and functions, and to check the types of the quantified variables.
    private int ids; // a counter for generating unique IDs for the e-graph nodes.
    public NormalFormVisitor(ModelEnv modelEnv) {
        this.modelEnv = modelEnv;
        this.normalForms = new java.util.ArrayList<>();
    }
    public NormalFormVisitor() {
        this(new ModelEnv());
    }
    @Override
    public EGraphNode visit(ModelUnit mu, NormalForm arg) {
        for (SigDecl sig : mu.getSigDeclList()) {
            sig.accept(this, arg);
        }
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ModuleDecl md, NormalForm arg) {
        modelEnv.setModuleName(md.getModelName());
        return new EGraphNode(0, Opcode.MODULEDECL, null, false, 0, false, Metatype.CONTROL);
    }
    @Override
    public EGraphNode visit(OpenDecl open, NormalForm arg) {
        modelEnv.addOpen(open.getAlias() + ": " + open.getFileName());
        return new EGraphNode(0, Opcode.OPEN, null, false, 0, false, Metatype.CONTROL);
    }
    @Override
    public EGraphNode visit(SigDecl sig, NormalForm arg) {
        modelEnv.addSig(sig.getName());
        for (FieldDecl field : sig.getFieldList()) {
            field.accept(this, arg);
        }
        return new EGraphNode(0, Opcode.SIGDECL, null, false, ids, false, Metatype.CONTROL);
    }
    @Override
    public EGraphNode visit(FieldDecl field, NormalForm arg) {
        // TODO: FIELDDECL IS A RELDECL. HOW TO HANDLE THIS? -> for all atoms out of 
        for (String name : field.getNames()) {
            modelEnv.addField(name);
        }
        field.getExpr().accept(this, arg);
        return new EGraphNode(0, Opcode.FIELDDECL, null, false, ids, false, Metatype.CONTROL);
    }
    @Override
    public EGraphNode visit(ParamDecl param, NormalForm arg) {
        if (arg == null) {
            throw new IllegalArgumentException("[Visitor] ParamDecl needs a valid predicate or function NormalForm as argument, but got null.");
        }
        for (ExprOrFormula var : param.getVariables()) {
            if (var instanceof VarExpr) {
                QuantiVar paramVar = new QuantiVar(- (arg.getParams().size() + 1), ((VarExpr) var).getName(), var.getType()); 
                // use negative De Bruijn indices for parameters, to distinguish them from quantified variables in the matrix, which use non-negative De Bruijn indices.
                arg.addParam(paramVar);
                var.accept(this, arg);
            } else {
                throw new IllegalArgumentException("[Visitor] ParamDecl variables should be VarExpr, but got: " + var.getClass().getSimpleName());
            }
        }
        return new EGraphNode(0, Opcode.PARAMDECL, null, false, ids, false, Metatype.CONTROL);
    }
    @Override
    public EGraphNode visit(VarDecl vard, NormalForm arg) {
        // TODO This is a RelDecl granting a new QTN
        
        if (!(vard.getParent() instanceof QtExpr || vard.getParent() instanceof QtFormula)) {
            throw new UnsupportedOperationException("Unimplemented method 'visit'");
        }
        if (vard.getParent() instanceof QtExpr) {
            QtExpr parentQtExpr = (QtExpr) vard.getParent();
            List<QuantiVar> vars = new ArrayList<>();
            // QuantificationTreeNode qtNode = 
            // new QuantificationTreeNode(parentQtExpr.getOp(), , parentQtExpr.isDisj(), vard.getType());
        }
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ExprOrFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(SigExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(FieldExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(VarExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(UnaryExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(UnaryFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(BinaryExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(BinaryFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ListExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ListFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(CallExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(CallFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(QtExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(QtFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ITEExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ITEFormula arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(LetExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(ConstExpr arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Body arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Predicate arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Function arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Fact arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Assertion arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Run arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }
    @Override
    public EGraphNode visit(Check arg0, NormalForm arg1) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'visit'");
    }


}
